[package]
name = "rdkafka"
version = "0.13.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
repository = "https://github.com/fede1024/rust-rdkafka"
readme = "README.md"
license = "MIT"
description = "Rust wrapper for librdkafka"
keywords = ["kafka", "rdkafka"]
categories = ["api-bindings"]

[dependencies]
rdkafka-sys = { path = "rdkafka-sys", version = "0.11.1-0" }
futures = "^0.1.13"
libc = "^0.2.0"
log = "^0.3.0"
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_json = "^1.0.0"

[dev-dependencies]
chrono = "^0.4.0"
clap = "^2.18.0"
env_logger = "0.4.0"
futures-cpupool = "^0.1.2"
rand = "^0.3.15"
tokio-core = "^0.1.4"

[features]
default = []

ssl = ["rdkafka-sys/ssl"]
sasl = ["rdkafka-sys/sasl", "ssl"]
dynamic_linking = ["rdkafka-sys/dynamic_linking"]
