[package]
name = "rdkafka-sys"
version = "0.11.3-0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
build = "build.rs"
links = "rdkafka"
repository = "https://github.com/fede1024/rust-rdkafka"
license = "MIT"
description = "Native bindings to the librdkafka library"
keywords = ["kafka", "rdkafka"]
categories = ["external-ffi-bindings"]

[dependencies]
lz4-sys = "^ 1.0"
libz-sys = "^ 1.0"
openssl-sys = { version = "~ 0.9.0", optional = true }

[build-dependencies]
num_cpus = "^0.2.0"
pkg-config = "^0.3.9"

[lib]
name = "rdkafka_sys"
path = "src/lib.rs"

[features]
default = []

ssl = ["openssl-sys"]
sasl = ["ssl"]
dynamic_linking = []
